### ISSUE TITLE
Doesn't work with subdomains

### ISSUE THREAD

**Issue by tomsommer** [JohNan/certbot-dns-simply#4]
Just FYI, this doesn't work for subdomains. 

Your implementation calls `https://api.simply.com/2/my/products/foo.example.com/dns/records/`, but it should call `https://api.simply.com/2/my/products/[objectid]/dns/records/`.

It should discover the correct objectid by calling https://api.simply.com/2/my/products/ first. 
An alternative would be to add `objectid` as a config argument.

**Comment by JohNan** [comment]
Thank you for your input. I will look into it asap. 

Feel free to help out and open up a pull request 😊

**Comment by JohNan** [comment]
> Just FYI, this doesn't work for subdomains.
> 
> Your implementation calls `https://api.simply.com/2/my/products/foo.example.com/dns/records/`, but it should call `https://api.simply.com/2/my/products/[objectid]/dns/records/`.
> 
> It should discover the correct objectid by calling https://api.simply.com/2/my/products/ first. An alternative would be to add `objectid` as a config argument.

When I call https://api.simply.com/2/my/products for my account I get the following response and can't see any `objectId`  in there. 

```json
{
  "products": [
    {
      "object": "mydomain.se",
      "name": "mydomain.se",
      "autorenew": true,
      "cancelled": false,
      "domain": {
        "name": "mydomain.se",
        "name_idn": "mydomain.se"
      },
      "product": {
        "id": 3,
        "name": "standardsuite",
        "date_created": 1189980000,
        "date_expire": 1758060000
      },
      "usernames": {
       ... 
      },
      "servers": {
       ... 
        }
      }
    },
    {
      "object": "mydomain2.nu",
      "name": "mydomain2.nu",
      "autorenew": true,
      "cancelled": false,
      "domain": {
        "name": "mydomain2.nu",
        "name_idn": "mydomain2.nu"
      },
      "product": {
        "id": 1,
        "name": "dnsservice",
        "date_created": 1695716709,
        "date_expire": false
      }
    }
  ],
  "status": 200,
  "message": "success"
}
```

The swagger documentation has this as an example for the dns records endpoint

```
The product handle, as found in the /my/products/ endpoint.
Example : example.com
```

So if I understand it correctly I should call `https://api.simply.com/2/my/products/mydomain.se/dns/records/` where the name in the payload should be the subdomain?

**Comment by JohNan** [comment]
> "object" is "objectid" :)
> 
> You should find the "object" that has the domain based on
> 
> ```
>    "domain": {
>         "name": "mydomain2.nu",
>         "name_idn": "mydomain2.nu"
>       },
> ```
> 
> because the object could be any string, it's just often the domain (non-IDN encoded), so you can't just use the provided domain. Also you need to take into account the values `foo.bar.co.uk` and `foo.bar.exampleæøå.com` and `foo.bar.xn--example-kxai4p.com`. I imagine this is very similar to other implementations.

Thank you for the clarification! 
It looks like the latest fix didn't take all this into account. I will look into this!

**Comment by JohNan** [comment]
@tomsommer Do you mind having a look at this pr: https://github.com/JohNan/certbot-dns-simply/pull/6 ?
